<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SentinelaAPI.Application\SentinelaAPI.Application.csproj" />
    <ProjectReference Include="..\SentinelaAPI.Domain\SentinelaAPI.Domain.csproj" />
  </ItemGroup>

</Project>
